# Generated by Django 5.0.6 on 2026-01-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_ingest_demo_mp3s"),
        ("catalog", "0004_seed_demo_assets"),
    ]

    operations = []
