# Generated by Django 5.0.6 on 2026-01-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_usernote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNote",
        ),
    ]
